Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 Numpy 기반으로 작성되어 있으며, 알고리즘의 입출력 데이터를 Numpy 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.nddrray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드캐스팅 가능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너 

In [2]:
import numpy as np
z=np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [5]:
my_arr = np.arange(1000000)
my_list=list(range(1000000))

In [8]:
%time for _ in range(10): my_array2=my_arr*2

Wall time: 11 ms


In [10]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 595 ms


In [12]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분포에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열 매트릭스
print(data,'\n')
print(data * 10, '\n')
print(data + data)

[[-1.10592093 -0.30519615  0.4775397 ]
 [ 2.13589761 -0.20624694 -0.70396066]] 

[[-11.05920931  -3.05196154   4.77539696]
 [ 21.35897607  -2.06246936  -7.03960659]] 

[[-2.21184186 -0.61039231  0.95507939]
 [ 4.27179521 -0.41249387 -1.40792132]]


In [13]:
print(data.shape) # 크기
print(data.dtype) # 데이터 타입
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE='width:300px;'>

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]] 
print(type(data2),'\n')
arr2=np.array(data2)
print(arr2,type(arr2))


<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [16]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [18]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
 # (,열)dl dksls (열,) 형태로 출력

[1 2 3] <class 'numpy.ndarray'> (3,)


In [21]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터
array2 = np.array([[1,2,3],[4,5,6]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [22]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열
array3 = np.array([[4,5,6]])
print(array3,type(array3),array3.shape)

[[4 5 6]] <class 'numpy.ndarray'> (1, 3)


In [30]:
# 3차원
array4 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                 [[2,4,6,8,10],[10,8,6,4,2]],
                 [[1,3,5,7,9],[9,7,5,3,1]]])
print(array4,type(array4),array4.shape,'\n')

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 2  4  6  8 10]
  [10  8  6  4  2]]

 [[ 1  3  5  7  9]
  [ 9  7  5  3  1]]] <class 'numpy.ndarray'> (3, 2, 5) 



In [31]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [32]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [33]:
print(np.ones(10),'\n')
print(np.ones((3,6)),'\n')
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [34]:
ar1 = np.full((2,2),5)
ar1

array([[5, 5],
       [5, 5]])

In [35]:
# 항등행렬, 단위행렬
ar2 = np.eye(3)
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [37]:
# arange 함수 : python의 range 함수의 배열 버전
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr2 = arr1.reshape(3,5)
print(arr2,arr2.shape,'\n')
arr3 = arr1.reshape(1,3,5)
print(arr3, arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [43]:
# Q. array1에 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1=np.arange(10)
array2=array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
# 0~29 일차원 배열을 생성한 후 다시 2,3차원 배열로 변환하여 출력하세요.
arr1 = np.arange(30)
arr2 = arr1.reshape(5,6)
arr3 = arr1.reshape(3,2,5)
print(arr1, arr1.shape,'\n')
print(arr2, arr2.shape,'\n')
print(arr3, arr3.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [45]:
# reshape(-1,-1) 이용, 차원 변경
arr1 = np.arange(30)
arr12 = arr1.reshape(5,-1) # 입력한 값에 따라 알아서 설정
print(arr12,arr12.shape,'\n')
arr13 = arr1.reshape(-1,2,5)
print(arr13,arr13.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [51]:
# 2 -> 1,3 차원으로 변환하여 출력
print(arr12,'\n')
arr21 = arr12.reshape(-1,)
arr31 = arr12.reshape(2,5,-1)
print(arr21,arr21.shape,'\n')
print(arr31,arr31.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]] (2, 5, 3)


In [52]:
# 3 -> 1,2 차원으로 변환하여 출력
print(arr31,'\n')
ar1 = arr31.reshape(-1,)
ar2 = arr31.reshape(-1,5)
print(ar1,ar1.shape,'\n')
print(ar2,ar2.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] (6, 5)


행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행령 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [53]:
# 정방행렬
a = np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [54]:
# 항등행렬, 단위행렬
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ndarray 데이터 형태 지정 및 변경
<img src = '데이터형태.jpg' STYLE='width:300px;'>

In [57]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2,arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [58]:
# 타입 변경 astype()
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [69]:
# empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다. cf. zeros()
# empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.
print(np.empty(shape=(10,), dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]


In [65]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype='S')
arr = np.array([1,2,3,4], dtype=np.string_)
print(arr, arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [62]:
arr1 = arr.astype(float)
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float64


In [73]:
# 정수와 실수로 구성된 list_e = [1,2,2,3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요.
list_e = [1,2,2,3,3]
arr=np.array(list_e)
arr.astype(int)
print(arr,arr.dtype)
arr2=arr.astype(float)
print(arr2,arr2.dtype)

[1 2 2 3 3] int32
[1. 2. 2. 3. 3.] float64


In [74]:
# 배열의 산술 연산
arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [75]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [76]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [77]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [79]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [90]:
# 기본 사칙연산
v1 = np.arange(1,10).reshape(3,3)
v2 = np.arange(11,20).reshape(3,3)

print(v1+v2,'\n')
print(np.add(v1,v2),'\n')
print(v2-v1,'\n')
print(np.subtract(v2,v1),'\n')
print(v1*v2,'\n')
print(np.multiply(v1,v2),'\n')
print(v2/v1,'\n')
print(np.divide(v2,v1))

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [95]:
arr = np.random.randn(2,2)
arr

array([[-0.87715759,  0.24706595],
       [-1.90979044, -0.09098135]])

In [96]:
arr.mean().round(4)

-0.6577

In [97]:
arr.mean(axis=1)

array([-0.31504582, -1.0003859 ])

In [100]:
arr.mean(axis=0)

array([-1.39347401,  0.0780423 ])

In [101]:
arr.sum().round(4)

-2.6309

In [102]:
arr.cumprod()

array([-0.87715759, -0.21671577,  0.41388171, -0.03765552])

In [103]:
# 인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr2d[2]

array([7, 8, 9])

In [108]:
arr2d[2][2]

9

In [115]:
arr2d[:,0]

array([1, 4, 7])

In [118]:
arr2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# arr2d를 다른 방식으로 아래와 같이 출력하세요.
[[1,2,3],
 [4,5,6]]

In [131]:
arr2d[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [119]:
# arr2d에서 [3,6],[[1,2],[4,5]]을 출력하세요.
print(arr2d[:2,2])
print()
print(arr2d[:2,:2])

[3 6]

[[1 2]
 [4 5]]


In [132]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
[14,15,16]
[3,9]
[1,7,13]

In [148]:
arr[2,2:5]


array([14, 15, 16])

In [173]:
arr[[0,1],3]

array([3, 9])

In [184]:
arr[:3,1]
arr[[0,1,2],1]

array([ 1,  7, 13])

In [185]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li,type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [191]:
# Boolean indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [195]:
# arr1d에서 일반 인덱스를 이용해서 [6 7 8 9]를 출력하세요.
print(arr1d[5:])

[6 7 8 9]


In [202]:
# Q. 1 ~ 14 까지의 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 boolean 인덱싱으로 출력
array_e = np.arange(15)
print(array_e[array_e/2 > 5])

[11 12 13 14]


In [199]:
names = np.array(['Bob','Joe','Will','Bob',"will",'joe','joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'will' 'joe' 'joe'] 

[[ 0.84018891  1.56924131 -0.49406331 -0.78941544]
 [ 2.22130178 -1.26977578 -0.6175739   1.22812665]
 [-0.66798985 -0.08387947  0.82759317 -0.72117709]
 [-0.51251733 -0.9271782  -1.47562007 -1.44366835]
 [ 0.00788121  1.91013542 -1.48650318 -0.70890341]
 [-0.55909732  1.79374464 -0.1854024  -0.93414249]
 [ 1.10905967  0.68422402  0.10502296  0.24069467]]


In [203]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [204]:
data[names=='Bob']

array([[ 0.84018891,  1.56924131, -0.49406331, -0.78941544],
       [-0.51251733, -0.9271782 , -1.47562007, -1.44366835]])

In [205]:
data[names=='Bob',2:]

array([[-0.49406331, -0.78941544],
       [-1.47562007, -1.44366835]])

In [206]:
data[names != 'Bob']

array([[ 2.22130178, -1.26977578, -0.6175739 ,  1.22812665],
       [-0.66798985, -0.08387947,  0.82759317, -0.72117709],
       [ 0.00788121,  1.91013542, -1.48650318, -0.70890341],
       [-0.55909732,  1.79374464, -0.1854024 , -0.93414249],
       [ 1.10905967,  0.68422402,  0.10502296,  0.24069467]])

In [226]:
# Bob이거나 Will인 것 출력
data[(names == 'Bob') | (names=='Will')]
mask = (names == 'Bob') | (names=='Will')
data[mask]

array([[ 0.84018891,  1.56924131, -0.49406331, -0.78941544],
       [-0.66798985, -0.08387947,  0.82759317, -0.72117709],
       [-0.51251733, -0.9271782 , -1.47562007, -1.44366835]])

In [228]:
# 음수를 모두 0으로 처리하여 출력
data[data<0]=0
print(data)

[[0.84018891 1.56924131 0.         0.        ]
 [2.22130178 0.         0.         1.22812665]
 [0.         0.         0.82759317 0.        ]
 [0.         0.         0.         0.        ]
 [0.00788121 1.91013542 0.         0.        ]
 [0.         1.79374464 0.         0.        ]
 [1.10905967 0.68422402 0.10502296 0.24069467]]


In [244]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력 (for문,배열 두가지 방식)
li=[]
for i in range(1,101):
    if i % 3 == 0:
        li.append(i)
print(li,'\n')

arr = np.arange(1,101)
print(arr[arr%3==0])
    

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99] 

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [250]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력 (for문,배열 두가지 방식)
li=[]
for i in range(1,101):
    if i % 5 == 0 and i % 2 ==0:
        li.append(i)
print(li,'\n')

arr = np.arange(1,101)
print(arr[(arr%5==0) & (arr%2==0)])

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100] 

[ 10  20  30  40  50  60  70  80  90 100]


In [270]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
arr = np.random.randn(5,5)
print(arr,'\n')
print(arr.mean())
print(np.std(arr))

[[-0.40926731 -2.34080607 -0.20474715 -1.43682172  0.7822186 ]
 [-0.9319652  -2.09853301  2.09083527  0.94470534  0.26540013]
 [ 1.71666258 -0.90306254 -1.50488965 -1.00465801 -0.82091576]
 [-0.19586734 -1.2869266   1.95413303 -0.82409959  0.03515676]
 [-1.13209728  1.12918654  0.24546472 -0.4448283   0.27088308]] 

-0.24419358023180315
1.170869806210642


In [271]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
np.version.version

'1.21.2'

In [272]:
# [과제] numpy 함수의 도움말 기능을 볼 수 있는 방법을 수행하여 add함수의 가이드를 출력하세요.
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [237]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [310]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr=np.arange(10)
print(arr)
print(np.sort(arr)[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [316]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
li = [1,2,0,0,4,0]
arr = np.array(li)
arr
arr[arr!=0]

array([1, 2, 4])