In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,size=(5,5))
arr

array([[5, 9, 1, 9, 8],
       [6, 5, 3, 7, 1],
       [4, 3, 9, 8, 6],
       [7, 5, 7, 2, 5],
       [9, 1, 3, 2, 9]])

In [7]:
# 전치
arr.T
np.transpose(arr)

array([[5, 6, 4, 7, 9],
       [9, 5, 3, 5, 1],
       [1, 3, 9, 7, 3],
       [9, 7, 8, 2, 2],
       [8, 1, 6, 5, 9]])

In [8]:
# 행렬곱, 내적
np.dot(arr.T,arr)

array([[207, 131, 135, 151, 186],
       [131, 141,  89, 152, 129],
       [135,  89, 149, 122, 127],
       [151, 152, 122, 202, 155],
       [186, 129, 127, 155, 207]])

In [10]:
a=np.arange(6).reshape(2,3)
print(a,'\n')

y=np.swapaxes(a, 0,1) # 0은 2차원(열), 1은 1차원(행)
print(y)
y.T

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]]
print(arr)

#################################
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)



[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [44]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a=np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y=np.transpose(a,(1,0,2))
print(y,y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3)


In [48]:
# (1,2,3) -> (2,3,1)
a=np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y=np.transpose(a,(1,2,0))
print(y,y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [57]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
arr=np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

arr_r=np.transpose(arr,(1,0,2))
print(arr_r,arr_r.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [56]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요
arr=np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

arr_r=np.transpose(arr,(0,2,1))
print(arr_r,arr_r.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


In [7]:
# 차원 변경 swapaxes
arr=np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
print(arr.swapaxes(1,2)) # ( 바꾸고자 하는 자리 두개 입력 )

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [58]:
# 나머지를 구할 경우 사용하는 함수
value1=np.array([15,30,45])
value2=np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [60]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')

value1 = np.array([100],dtype=int)
print(value1,'\n')
print(np.reciprocal(value1, dtype=float))

[1.17647059 0.54054054 1.         0.01      ] 

[100] 

[0.01]


In [61]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1, value2))

[  4 100 225] 

[   2  100 3375]


In [62]:
arr = np.random.randn(100000000)
print(arr.mean(),'\n')
print(arr.std())

8.272179117160036e-05 

0.9999874322383739


In [63]:
# 양수인 원소의 개수
(arr > 0).sum()

49996726

In [64]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False,False,True,True])
bools.any()

True

In [65]:
# 모든 원소가 True인지 검사
bools.all()

False

In [68]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0,2,-2) # (조건, if , else)

[[-0.3393284   1.23146729  1.82156368 -0.64584634]
 [-3.07026257 -0.04753562  1.41583965  0.50478723]
 [ 0.07972     0.11062279  0.12866452 -1.05837873]
 [-0.24774231 -0.15169818 -1.07398568  1.21862321]] 



array([[-2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2,  2,  2, -2],
       [-2, -2, -2,  2]])

In [70]:
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0,2,arr)

[[-0.82996085 -1.26861638  0.7052644  -1.16899762]
 [-1.85037414 -0.6235535   0.25525975  0.42095591]
 [-1.10979879  0.83871029  0.15674435  1.23511583]
 [-0.20936101  0.18855229  1.04044657 -1.74122728]] 



array([[-0.82996085, -1.26861638,  2.        , -1.16899762],
       [-1.85037414, -0.6235535 ,  2.        ,  2.        ],
       [-1.10979879,  2.        ,  2.        ,  2.        ],
       [-0.20936101,  2.        ,  2.        , -1.74122728]])

In [71]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열 2개 반환
x=np.arange(1,4)
y=np.arange(1,4)
xs,ys=np.meshgrid(x,y)
print(xs,'\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [72]:
# np.sort()
np.random.seed(0)
arr=np.random.randint(1,100,size=10)
print(arr,'\n')
print(np.sort(arr),'\n')

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 



In [73]:
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [76]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_arr2d_axis0=np.sort(arr2d, axis=0)
print(sort_arr2d_axis0,'\n')
sort_arr2d_axis1=np.sort(arr2d, axis=1)
print(sort_arr2d_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [79]:
# ndarray.sort() : 원본 반영
arr = np.random.randint(1,10,size=10)
print(arr,'\n')
arr.sort() #원본 반영
arr

[2 4 4 4 8 1 2 1 5 8] 



array([1, 1, 2, 2, 4, 4, 4, 5, 8, 8])

In [83]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
np.random.seed(0)
arr=np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [84]:
np.random.seed(0)
arr=np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [85]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [87]:
# 배열에서 정렬한 후 5%에 해당되는 원소만 출력

large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

-1.6155165121891895

In [4]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [5]:
names=names.tolist()
sorted(set(names))

['Bob', 'Joe', 'Will']

In [6]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 boolean 배열을 반환
values=np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [7]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr=np.arange(10)
np.save('some_array',arr)

In [8]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [10]:
arch=np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# Q. 인덱싱을 사용하여 [[1 0 1 0 1 0 1 0] 1 0]을 출력하세요.
a=np.ones(10,dtype=int)
for i in range(len(a)):
    if i % 2 == 1:
        a[i]=0
a


array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [53]:
# Q. a = np.arange(10) 에서 [6,7,8,9] 출력
a = np.arange(10)
print(a[a>5])

[6 7 8 9]


In [54]:
# Q. a에서 최대값, 최소값 인덱스 출력
a = np.arange(10)
print(f'최대값 : {np.argmax(a)}\n최솟값 : {np.argmin(a)}')

최대값 : 9
최솟값 : 0


In [56]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요.
a = np.arange(10)
np.argsort(a)[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [60]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

a=np.ones((10,10))
a[1:9,1:9]=0
a


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [60]:
a=np.ones((5,5))
b=np.zeros((9,9))
b[2:7,2:7]=a
b
# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# pad
arr = np.ones((5,5))
np.pad(arr,((2,2),(2,2)),'constant',constant_values = 0)


In [8]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(인덱싱,tile함수 두가지)
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])

a=np.zeros((8,8),dtype=np.int32)
for i in range(8):
    for j in range(8):
        if i%2==0:
            if (j+1) % 2 == 0:
                a[i][j]=1
        else:
            if (j) % 2 == 0:
                a[i][j]=1

a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [16]:
a=np.array([[0,1],[1,0]])
print(np.tile(a,(4,4)))




[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# [도전과제] np.arange(4)을 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [95]:
a=np.arange(4)+1
a
np.diag(a,-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [49]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
a=np.arange(336).reshape(6,7,8)
x=int(input('숫자 입력  : '))
flag=False
for i in range(6):
    for j in range(7):
        if x < 56:
            flag=True
            print(f'[{i}][{j}][{x}]')
            break
        
            
    if flag==True:
        break



숫자 입력  : 51
[0][0][51]


In [9]:
a=np.arange(336).reshape(6,7,8)
print(a,'\n')
x,y,z=np.where(a==99)

print(x,y,z)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [11]:
arr = np.arange(336).reshape(6,7,8)
# print(arr)
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


[파이썬 random 함수]

In [139]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴 
print(random.uniform(10,20),'\n') # min max 사이 float 리턴
print(random.randrange(10),'\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li=[1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.3822862689576242 

6 

14.687179629071943 

1 

3 

[5, 1, 2] 

[1, 3, 2, 4, 5]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 균일분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [141]:
print(np.random.randint(6),'\n') # 0 ~ 5 까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19 까지 정수인 난수 1개
print(np.random.randint(10,size=10),'\n') # 0 ~ 9 까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19 까지 정수인 난수 10개
print(np.random.randint(10,20,size=(3,5))) # 10 ~ 19 까지 정수인 난수로 3행5열 배열 생성

4 

9 

[1 4 0 7 2 9 5 2 4 5] 

[15 17 16 14 18 18 12 15 19 12] 

[[18 18 17 12 13]
 [10 10 16 18 11]
 [14 18 12 13 14]]


In [144]:
# 0 ~ 1 사이의 균일분포
r=np.random.rand(6)
r.mean()

0.22858312889067137

In [143]:
# 표준 정규분포
r=np.random.randn(6)
r.mean()

-0.31608869878054885

In [145]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([3, 2, 4, 1, 5])

In [146]:
np.random.choice(list)

2

In [147]:
a=np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts=True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [148]:
np.random.uniform(1.0, 2.0, 10)

array([1.52445459, 1.09710711, 1.95512104, 1.48329626, 1.94362462,
       1.56910829, 1.35306903, 1.3794604 , 1.31201155, 1.72072822])

In [150]:
print(np.random.uniform(0,1,(2,3)))

[[0.72625696 0.25760629 0.57936447]
 [0.97143689 0.00628718 0.04544402]]


In [149]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.04125462, 0.44981262, 0.92855678],
       [0.71876349, 0.86017736, 0.9772561 ]])

In [65]:
ar = np.random.rand(4,8)
ar

array([[0.88892791, 0.70830197, 0.0203275 , 0.30435288, 0.90464692,
        0.4923864 , 0.32952826, 0.92966515],
       [0.09576313, 0.18258003, 0.55351678, 0.14937886, 0.90839131,
        0.92690822, 0.58383838, 0.86166384],
       [0.64120151, 0.60290574, 0.38254954, 0.59525743, 0.53872558,
        0.93268279, 0.25279956, 0.06961872],
       [0.40858876, 0.25173689, 0.5302599 , 0.28488694, 0.93214341,
        0.22335254, 0.45682182, 0.12231148]])

In [12]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df=pd.DataFrame(ar)
print(df,type(df))

NameError: name 'ar' is not defined

In [155]:
print(df[0])
type(df[0])

0    0.266221
1    0.342841
2    0.910915
3    0.749471
Name: 0, dtype: float64


pandas.core.series.Series

In [156]:
columns = ['id','gender','age','region','prodict','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   prodict     price       qty  \
0  0.266221  0.424350  0.226256  0.845722  0.117812  0.557667  0.465169   
1  0.342841  0.640393  0.138328  0.316037  0.434721  0.289108  0.964271   
2  0.910915  0.040306  0.769267  0.901340  0.061121  0.525520  0.829479   
3  0.749471  0.087045  0.143115  0.622292  0.217566  0.035418  0.711940   

       time  
0  0.928044  
1  0.610234  
2  0.006982  
3  0.459561

In [175]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요.
gen=['남자','여자']
irr= np.random.randint(1000,10000,3)
grr= np.random.choice(gen,3)
arr= np.random.randint(1,100,3)
data=np.array([irr,grr,arr]).transpose()


col=['id','gender','age']
index=[np.arange(3)]
df=pd.DataFrame(data,index,columns=col)
df




id gender age
0  2566     남자  52
1  7077     여자  27
2  7323     여자  13

In [182]:
ar = np.zeros((4,3))
col=['id','gender','age']
index=[np.arange(4)]
df = pd.DataFrame(ar,index,columns=col)
df.id=np.random.randint(1000,10000,4)
df.gender=np.random.choice(['남','여'],4)
df.age=np.random.randint(10,80,4)
df

id gender  age
0  1574      남   48
1  5357      여   50
2  7452      남   28
3  2583      여   72

[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측치 1000개)

- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [17]:
arr = np.zeros((1000,15))
col=['id','gender','age','region','product_19','product_20','price_19','price_20'
    ,'quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index=[np.arange(1000)+1]
df=pd.DataFrame(arr,index,columns=col)
df.id=np.arange(1,1001)
df.gender=np.random.randint(2,size=1000)
df.age=np.random.randint(80,size=1000)
df.region=np.random.randint(1,11,size=1000)
df.product_19=np.random.randint(11111,100000,size=1000)
df.product_20=np.random.randint(11111,100000,size=1000)
df.price_19=np.random.randint(1000,50001,size=1000)
df.price_20=np.random.randint(1000,50001,size=1000)
df.quantity_19=np.random.randint(1,101,1000)
df.quantity_20=np.random.randint(1,101,1000)
df.time_19=np.random.randint(1,25,size=1000)
df.time_20=np.random.randint(1,25,size=1000)
df.amount_19=df.price_19*df.quantity_19
df.amount_20=df.price_20*df.quantity_20
df.sales=np.where(df.amount_20 > df.amount_19,1,0)
df

id  gender  age  region  product_19  product_20  price_19  price_20  \
1        1       0   60       4       52299       21704     40324     18639   
2        2       0   47       3       84176       55486     28720     49529   
3        3       1   32       8       26013       76495     10580     41425   
4        4       1   17       4       97168       90809      1103     26432   
5        5       0   70       7       61695       66533     22668      4259   
...    ...     ...  ...     ...         ...         ...       ...       ...   
996    996       1   11       2       89575       33449     30264     11595   
997    997       0    5       8       72814       76971     30162      2705   
998    998       0   23       7       66991       26828     33700     10973   
999    999       0   48       7       98984       27180      4644      7689   
1000  1000       0    1       6       17599       36143     18153      9314   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              81           80       10       10    3266244    1491120      0  
2              11           91        4       13     315920    4507139      1  
3              73           79       18       21     772340    3272575      1  
4               9           36        5       16       9927     951552      1  
5              56           70       13        9    1269408     298130      0  
...           ...          ...      ...      ...        ...        ...    ...  
996            62           49       22        3    1876368     568155      0  
997             3           23       18       24      90486      62215      0  
998             6           95       13        4     202200    1042435      1  
999            90           59        5       15     417960     453651      1  
1000           11           15       15       13     199683     139710      0  

[1000 rows x 15 columns]

In [18]:
print(len(df[df.sales==1]))
df[df.sales==1]

494


id  gender  age  region  product_19  product_20  price_19  price_20  \
2      2       0   47       3       84176       55486     28720     49529   
3      3       1   32       8       26013       76495     10580     41425   
4      4       1   17       4       97168       90809      1103     26432   
7      7       1   24       4       47939       85058     39543     24942   
12    12       1   57      10       84533       73337     39739     49850   
..   ...     ...  ...     ...         ...         ...       ...       ...   
991  991       0   33       6       96628       58932      7229     25477   
992  992       1    3       2       91439       67037      3427     49313   
993  993       0   72       4       76672       51324     21504     22365   
998  998       0   23       7       66991       26828     33700     10973   
999  999       0   48       7       98984       27180      4644      7689   

     quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
2             11           91        4       13     315920    4507139      1  
3             73           79       18       21     772340    3272575      1  
4              9           36        5       16       9927     951552      1  
7             46           74       18       24    1818978    1845708      1  
12             8           95       23       23     317912    4735750      1  
..           ...          ...      ...      ...        ...        ...    ...  
991           20           52       16        3     144580    1324804      1  
992           72            8       24        8     246744     394504      1  
993           12           34        4       19     258048     760410      1  
998            6           95       13        4     202200    1042435      1  
999           90           59        5       15     417960     453651      1  

[494 rows x 15 columns]