## 판다스
- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)
- Contents
 - Series(변환, 인덱스 구조, 원소 선택)
 - DataFrmae(변환, 인덱스, 삭제, 선택, 추가, 변경, 전치 등)

In [2]:
# 시리즈 클래스 만들기
import pandas as pd

dic_data={'a':1, 'b':2, 'c':3}
sr=pd.Series(dic_data)
print(sr,type(sr))

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


In [2]:
# 리스트를 시리즈로 변환

list_data = ['2019-10-02', 3.14, 'ABC', 100, True]
sr=pd.Series(list_data, index=['a','b','c','d','e'])
print(sr,type(sr))

a    2019-10-02
b          3.14
c           ABC
d           100
e          True
dtype: object <class 'pandas.core.series.Series'>


In [4]:
idx=sr.index
print(idx,'\n')
val=sr.values
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object') 

['2019-10-02' 3.14 'ABC' 100 True]


In [3]:
# 튜플을 시리즈로 변환
tup_data = ('영인', '2015-05-01', '여', True)
sr = pd.Series(tup_data, index=['이름','생년월일','성별','학생여부'])
print(sr,type(sr))

이름              영인
생년월일    2015-05-01
성별               여
학생여부          True
dtype: object <class 'pandas.core.series.Series'>


In [9]:
print(sr[0])
print(sr['이름'])
print(sr[1:3])

영인
영인
생년월일    2015-05-01
성별               여
dtype: object


In [3]:
# 배열을 시리즈로 변환
import numpy as np
s1 = np.arange(start=11,stop=16)
s2 = pd.Series(s1, index=['ED1','ED2','ED3','ED4','ED5'])
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [15]:
print(s2[1:3],'\n')
print(s2[[1,3]])

ED2    12
ED3    13
dtype: int32 

ED2    12
ED4    14
dtype: int32


In [16]:
# 시리즈 -> 배열

print(type(s2))
ar = np.array(s2)
print(ar,type(ar))

<class 'pandas.core.series.Series'>
[11 12 13 14 15] <class 'numpy.ndarray'>


In [22]:
# Q. 4가지 자료형 데이터를 생성하고 각각 Series로 변환하여 출력하세요.
li1=['가','나','다']
tup1=(1,2,3)
dic1={'a':1,'b':2,'c':3}
arr1=np.array(['ㄱ','ㄴ','ㄷ'])

li_s = pd.Series(li1)
tup_s = pd.Series(tup1)
dic_s = pd.Series(dic1)
arr_s = pd.Series(arr1)

print(li_s, '\n')
print(tup_s, '\n')
print(dic_s, '\n')
print(arr_s)

0    가
1    나
2    다
dtype: object 

0    1
1    2
2    3
dtype: int64 

a    1
b    2
c    3
dtype: int64 

0    ㄱ
1    ㄴ
2    ㄷ
dtype: object


In [27]:
data=np.arange(1000,5000,1000)
obj=pd.Series(data)
state = ['Califonia','Ohio','Oregon','Texas']
obj.name='population'
obj.index=state
obj.index.name='state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [28]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [32]:
obj['Newyork'] = 3000
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Newyork      3000.0
Name: population, dtype: float64

In [33]:
obj.Newyork

3000.0

In [29]:
obj.isnull()

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

## 데이터프레임
- 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래
- 데이터프레임의 열은 각각 시리즈 개체
- 시리즈를 역벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 션형대수학에서 열 벡터(mx1행렬)는 m 원소들의 단일 열 행렬
- 행 벡터(!XM 헁렬은
- 리스트, 딕셔너리, 배열 등 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있음

In [38]:
# 배열 -> 데이터프레임
ar=np.random.randint(100,200,size=(3,3))
print(ar,type(ar),'\n')
df=pd.DataFrame(ar,index=['d1','d2','d3'],columns=['pd','sales','int'])
print(df,type(df))

[[141 167 138]
 [113 197 120]
 [152 170 191]] <class 'numpy.ndarray'> 

     pd  sales  int
d1  141    167  138
d2  113    197  120
d3  152    170  191 <class 'pandas.core.frame.DataFrame'>


pandas indexing
- iloc : integer localtion의 약어, 데이터프레임의 행이나 칼럼의 순서를 나타내는 정수로 특정 값을 추출해오는 방법
- loc : 인덱스명, 칼럼명을 직접 적거나 특정 조건식을 써줌으로써 사람이 읽기 좋은 방법으로 데이터에 접근하는 방법

In [39]:
# 행 선택
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       113
sales    197
int      120
Name: d2, dtype: int32 

pd       113
sales    197
int      120
Name: d2, dtype: int32


In [40]:
# 특정 행, 열 선택
print(df.iloc[1,1],'\n')
print(df.loc['d2','sales'])

197 

197


In [42]:
# 행, 열 추가 
df1=df.copy()
df1.loc['d5']=0 # 행 추가
df1

pd  sales  int
d1  141    167  138
d2  113    197  120
d3  152    170  191
d5    0      0    0

In [46]:
df1['pf']=np.random.randint(100,200) # 열 추가
df1

pd  sales  int   pf
d1  141  167.0  138  138
d2  113    NaN  120  138
d3  152  170.0  191  138
d5    0    0.0    0  138

In [43]:
# 원소 값 변경
df1.iloc[1,1] = np.nan
df1

pd  sales  int
d1  141  167.0  138
d2  113    NaN  120
d3  152  170.0  191
d5    0    0.0    0

In [4]:
# 사전 -> 데이터프레임
sp1=np.arange(1,6)
df = pd.DataFrame({
    'col1':sp1,'col2':sp1 * 2,'col3':['A','B','C','D','E']
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [5]:
# 리스트 -> 데이터프레임
a=np.random.randint(1,5,size=(10,5))
list1=a.tolist()
list1
index=np.arange(1,11)
df = pd.DataFrame(list1,index,columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
1    1   1   3   4   2
2    3   4   1   4   2
3    1   2   3   2   3
4    4   2   4   2   4
5    3   1   3   3   2
6    2   2   1   2   3
7    2   2   4   1   3
8    2   1   1   3   3
9    2   2   2   4   4
10   1   3   1   3   2

In [9]:
# 데이터프레임 -> 배열, 리스트, 딕셔너리
ar=df.values
print(ar,type(ar),'\n')
li=df.values.tolist()
print(li,type(li),'\n')
dic=df.to_dict('list')
print(dic,type(dic))

[[1 1 3 4 2]
 [3 4 1 4 2]
 [1 2 3 2 3]
 [4 2 4 2 4]
 [3 1 3 3 2]
 [2 2 1 2 3]
 [2 2 4 1 3]
 [2 1 1 3 3]
 [2 2 2 4 4]
 [1 3 1 3 2]] <class 'numpy.ndarray'> 

[[1, 1, 3, 4, 2], [3, 4, 1, 4, 2], [1, 2, 3, 2, 3], [4, 2, 4, 2, 4], [3, 1, 3, 3, 2], [2, 2, 1, 2, 3], [2, 2, 4, 1, 3], [2, 1, 1, 3, 3], [2, 2, 2, 4, 4], [1, 3, 1, 3, 2]] <class 'list'> 

{'c1': [1, 3, 1, 4, 3, 2, 2, 2, 2, 1], 'c2': [1, 4, 2, 2, 1, 2, 2, 1, 2, 3], 'c3': [3, 1, 3, 4, 3, 1, 4, 1, 2, 1], 'c4': [4, 4, 2, 2, 3, 2, 1, 3, 4, 3], 'c5': [2, 2, 3, 4, 2, 3, 3, 3, 4, 2]} <class 'dict'>


In [93]:
# Q. 배열, 리스트, 딕셔너리로 데이터프레임을 생성한 후 다시 배열, 리스트, 딕셔너리로 변환하여 출력하세요.
ar=np.random.randint(1,10,size=(5,4))
li=ar.tolist()

df_a=pd.DataFrame(ar,index=np.arange(1,6),columns=['a1','a2','a3','a4'])
df_l=pd.DataFrame(li,index=np.arange(1,6),columns=['l1','l2','l3','l4'])
df_d=pd.DataFrame({'d1':[1,2,3],'d2':[2,4,6],'d3':[3,6,9]})

ar_r=df_a.values
print(ar_r,type(ar_r),'\n')
li_r=df_l.values.tolist()
print(li_r,type(li_r),'\n')
dic=df_d.to_dict('list')
print(dic,type(dic))

[[5 1 3 7]
 [2 3 5 2]
 [6 6 7 4]
 [9 3 3 8]
 [4 4 2 9]] <class 'numpy.ndarray'> 

[[5, 1, 3, 7], [2, 3, 5, 2], [6, 6, 7, 4], [9, 3, 3, 8], [4, 4, 2, 9]] <class 'list'> 

{'d1': [1, 2, 3], 'd2': [2, 4, 6], 'd3': [3, 6, 9]} <class 'dict'>


In [96]:
# file 생성
li=['냉면','칼국수','잔치국수','수제비','우동']
df1=pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['차림표'])
df1.to_csv("C:\cakd5\workspace\m2_분석라이브러리활용\dataset/file_data_csv",index=None)
file_data=pd.read_csv("C:\cakd5\workspace\m2_분석라이브러리활용\dataset/file_data_csv")
file_data

차림표
0    냉면
1   칼국수
2  잔치국수
3   수제비
4    우동